<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>Joha Cryptor Asp Core </Title>
		<Version>0.0.2-alfa</Version>
		<Company>none</Company>
		<PackageProjectUrl>https://github.com/mirjahongir/JhDbCrypter</PackageProjectUrl>
		<RepositoryUrl>https://github.com/mirjahongir/JhDbCrypter</RepositoryUrl>
		<PackageReadmeFile></PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer">
		  <Version>10.0.5</Version>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.13" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer">
			<Version>9.0.14</Version>
		</PackageReference>
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer">
			<Version>8.0.25</Version>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.17.0" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
	</ItemGroup>
  <ItemGroup>
    
    <ProjectReference Include="..\JohaEfCrypter\JohaEfCrypter.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
